# Generated by Django 5.0.1 on 2024-01-17 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devtools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24, verbose_name='제목')),
                ('photo', models.ImageField(blank=True, upload_to='ideas/%Y%m%d', verbose_name='이미지')),
                ('content', models.CharField(max_length=24, verbose_name='내용')),
                ('interest', models.IntegerField(verbose_name='관심도')),
                ('is_starred', models.BooleanField(default=False, verbose_name='찜하기')),
                ('devtool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devtools.devtool', verbose_name='개발툴')),
            ],
        ),
    ]
